### ISSUE TITLE
Ensure all operations (non-overloads) have unique names

### ISSUE THREAD

**Issue by deyaaeldeen** [Azure/autorest.typescript#2035] opened 2023-09-26 01:03 UTC
Consider the following definitions for two APIs:

```
@route("/chat")
namespace Chat {
  @route("/completions")
  interface Completions {
    @tag("OpenAI")
    @post
    @operationId("createChatCompletion")
    create(
      @body body: CreateChatCompletionRequest,
    ): CreateChatCompletionResponse | ErrorResponse;
  }
}
@route("/completions")
interface Completions {
  @tag("OpenAI")
  @post
  @operationId("createCompletion")
  create(
    @body body: CreateCompletionRequest,
  ): CreateCompletionResponse | ErrorResponse;
}
```

Both operations are named `create` and the generated code names corresponding methods `create` which is not valid:
```ts
  create(
    model:
      | string
      | "gpt4"
      | "gpt-4-0314"
      | "gpt-4-0613"
      | "gpt-4-32k"
      | "gpt-4-32k-0314"
      | "gpt-4-32k-0613"
      | "gpt-3.5-turbo"
      | "gpt-3.5-turbo-16k"
      | "gpt-3.5-turbo-0301"
      | "gpt-3.5-turbo-0613"
      | "gpt-3.5-turbo-16k-0613",
    messages: ChatCompletionRequestMessage[],
    options: CreateOptions = { requestOptions: {} }
  ): Promise<CreateChatCompletionResponse> {
    return create(this._client, model, messages, options);
  }

create(
    model:
      | string
      | "babbage-002"
      | "davinci-002"
      | "text-davinci-003"
      | "text-davinci-002"
      | "text-davinci-001"
      | "code-davinci-002"
      | "text-curie-001"
      | "text-babbage-001"
      | "text-ada-001",
    prompt: string | string[] | number[] | number[],
    bestOf: number | null,
    options: CreateOptions = { requestOptions: {} }
  ): Promise<CreateCompletionResponse> {
    return create(this._client, model, prompt, bestOf, options);
  }
```

Causing this TS error:
```
src/OpenAIClient.ts(62,3): error TS2393: Duplicate function implementation.
```

**Comment by deyaaeldeen** [comment] 2023-09-26 01:23
This also causes the options bag type to be generated with the same name (`CreateOptions`) for all operations causing more type errors.

**Comment by qiaozha** [comment] 2023-09-26 13:33
Currently, this is by design, we will not use namespace name as the prefix In rlc layer, there is an option enableOperationGroup to add operation group name as prefix, we will also automatically detect the conflicts and try to resolve it with interface name as prefix but both of this two operation has the same interface name Completions, there's no way for codegen to know how to resolve the conflict.

**Comment by deyaaeldeen** [comment] 2023-09-26 14:02
At the end of the day, we shouldn't generate non-compiling code. Do we know what other languages emitters do in this case? Can we at least throw a helpful error message containing options for what to do next?

**Comment by MaryGao** [comment] 2023-10-08 09:44
I don't think we should resolve these conflicts in emitter side. 

For RLC we follow similar rules to OpenAPI3 to resolve them. See [tsp playground here](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdCI7CgpAc2VydmljZSh7CiAgdGl0bGU6ICJXaWRnZXQgU8YbIiwKfSkKbmFtZXNwYWNlIERlbW%2FHGzsKCnVzaW5nIFR5cGVTcGVjLkh0dHA70BVSZXN0xGxyb3V0ZSgiL2NoYXQizFNDaGF0IOQAgsojb21wbGV0aW9ucyIpCiAgaW50ZXJmxSzKGsUzICBAdGFnKCJPcGVuQUnFLSAgQHBvc3TFCmNyZWF0ZSjFDCk6IHZvaWQ7CiAgfQp96wCQzW3aa99p02l9&e=%40typespec%2Fopenapi3&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40typespec%2Fhttp%2Fall%22%5D%7D%7D) the operation id is duplicated also.

For Modular we leverage the `listClients` in tcgc to extract all models similar to other languages' emitter. In above case we have to customize these two ops in different @client or @operationGroup otherwise we'll get two ops with same name.

I notice Brain has a commit to resolve this https://github.com/bterlson/openai-in-typespec/commit/4efd423f3321ed8cb799974d3e5105f1e4ecc6df, not sure we should close this issue.

**Comment by deyaaeldeen** [comment] 2023-10-09 15:46
As a matter of principle, I think the emitter should never generate non-compiling code. If we end up in a situation where non-compiling code is about to be generated, we should throw a helpful error message instead. This will greatly improve the development experience for the library authors.

**Comment by MaryGao** [comment] 2023-10-11 02:52
>  If we end up in a situation where non-compiling code is about to be generated, we should throw a helpful error message instead.

I think the point is valid if the emitter can detect the generated code would be non-compiling due to known issue e.g operation name conflicts, reporting these info out would be helpful.

**Comment by bterlson** [comment] 2023-10-11 18:10
I think at a minimum we should throw an error or at least emit a warning for non-compiling code with a suggestion for how to fix the issue. For this case in particular, the intention was for the namespaces and interfaces to reflect the grouping I wanted in the client. I want to make sure, in a world where Deya's example compiles to a client with a shape like client.chat.completions.create() and client.completions.create(), that there are no other conflicts in either RLC or modular.

**Comment by MaryGao** [comment] 2023-10-12 15:42
Conflicts may arise among different interfaces or namespaces, and we currently only resolve them at the RLC layer for inter-interface conflicts. We can enhance our resolution rule as `Nearest Interface/Namespace Search`, as named it would search the nearest ones' pattern for these operations and then apply the pattern as name prefix or scope.

Namespace would be nested in tsp searching the nearest could help us not generate code like `client.a.b.c.d.e.create()`. So in Deya's case we could apply both interface and namespace for the conflict.

**RLC**

```typescript
  post(options?: ChatCompletionsCreateParameters): StreamableMethod<ChatCompletionsCreateXXXResponse>;
  post(options?: CompletionsCreateParameters): StreamableMethod<CompletionsCreateXXXResponse>;
```

**Modular classical layer**

```typescript
  client.chat.completions.create();
  client.completions.create();
```

**Modular API layer**

```typescript
  chatCompletionsCreate();
  completionsCreate();
```

**Comment by joheredi** [comment] 2023-10-16 17:22
I think I like it, so in summary:

RLC - Unchanged
Classical Client - Do your way through the namespace structure
Modular - build up the operation name similar to the classical structure but just on the name.

I guess another option for Modular would be to add sub-exports to match the namespaces, however, I think that can be a bit annoying to customers when they need to use operations from different namespaces, and they'll be forced to rename their imports. So I think having a name like this provides a smoother experience.

**Comment by joheredi** [comment] 2023-10-16 17:30
Also, let's implement this for branded and unbranded, we can keep a flag (namespaceGroupping defaulting to true) which can help us go back to the current state if needed. However, let's try to make this the default regardless of the branding

**Comment by joheredi** [comment] 2023-10-17 23:05
I was talking to @bterlson and we have a different proposal for the modular bits. Which is having multiple layers of sub-exports. UX would look like this:

```ts
import { createOpenAIContext } from "openai/api";
import {create} from "openai/api/audio/transcriptions"

//...

const result = await create(context, {
    file,
    model: "whisper-1",
    responseFormat: "verbose_json",
    language: "en",
    temperature: 0.9,
  });
```

Customers can use `import * as` to group operations if they want to

```ts
import { createOpenAIContext } from "openai/api";
import * as transcriptions from "openai/api/audio/transcriptions"
import * as translations from "openai/api/audio/translations"

//...

const result = await translations.create(context, {
    file,
    responseFormat: "verbose_json",
    language: "en",
    temperature: 0.9,
  });

const result = await transcriptions.create(context, {
    file,
    responseFormat: "verbose_json",
    language: "en",
    temperature: 0.9,
  });
```

**Comment by qiaozha** [comment] 2023-10-19 03:53
Consider a case like below
```
import "@typespec/rest";
import "@typespec/http";

using TypeSpec.Rest;
using TypeSpec.Http;

model A {
  propA1: string 
}

namespace B {
  model A {
    propA2: string;
  }
  interface C {
    op op1(@body body: A): void;
  }
  op op1(@body body: A): void;
}

@route("d")
interface D {
  op op1(@body body: A): void;
}
op op1(@body body: A): void;
```
In the Modular layer:  I can think of two ways to handle the model conflicts: 

- Option1: to have models subpath parrell with api subpath.
- Option2: to have independent models subpath based on where the models are actually layered.

If it's option1, we will have the follow subpath
```
openai/api
openai/models
openai/api/d
openai/models/d
openai/api/b
openai/models/b
openai/api/b/c
openai/models/b/c
```
where `openai/models` and `openai/models/d` have the same definition and `openai/models/b` of top level A. and `openai/models/b/c` have the same definition of A inside namespace B.

If it's option2 we will have the following subpath 
```
openai/api
openai/api/d
openai/api/b
openai/api/b/c
openai/models
openai/models/b
```
Customers who are using 
```
openai/api
openai/api/d
``` 
they will need to import A from `openai/models`.
And customers who are using 
```
openai/api/b
openai/api/b/c
```
They will need to import A from `openai/models/b`

A bref here:
Option1 may be more easier for customer to find the right model to import but may have too much duplicate models. And Option2 may be more clear to customer if they are familiar with the original TypeSpec. but maybe a little difficult for those who are not familiar with the TypeSpec to find the original models to import. 

Maybe we could have 
- Option3, to generate the file as Option2 suggested but provide subpath export as Option1 suggested ? 

In classical layer:  we will have a user experience like 
```
client.op1(a: A);
client.d.op1(a: A);
client.b.op1(a: A);
client.b.c.op1(a: A);
```
As we don't export any models in the classical client layer, see details here https://github.com/Azure/autorest.typescript/pull/1830#pullrequestreview-1533541356 and we will split into different files for different api subpath, so there's no model conflicts in the classical client layer.

In the RLC layer, 

As we put all those models into the same file, we will have to resolve the conflicts here. One possible solution I can think of is to use namespace and interface as the prefix or suffix for model A inside namespace B. we will get 

a. `BA` for A inside namespace B. and treat B as prefix
b. `AInB` for A inside namespace B, and treat B as suffix, here add an `In` to make it more readable. 

Here, I might prefer b if we are really taking this approach, because If I were a customer, I need to import a model, the first thing I would type is its name A and B doesn't really mean anything in the context of RLC.  

@joheredi @bterlson Could you help share your thoughts here ? Thanks.

**Comment by joheredi** [comment] 2023-10-19 04:58
I guess another option can be to keep the models in the same place `openai/models` and always build their name using their namespace hierarchy.

I think I prefer to compromise on the interface names and keep the UX easier for the customers. Different to other languages our customers don't need to import the model to construct it, so the scenarios where users are forced to import them are smaller and I would prefer to optimize for the organization of the operations without introducing another hierarchy for the models.

**Comment by qiaozha** [comment] 2023-10-19 13:50
Just realize we could refer to another namespace's model. like in the above example, we can define the body type of op1 inside interface D as B.A;
```
@route("d")
interface D {
  op op1(@body body: B.A): void;
}
op op1(@body body: A): void;
```
This could be an strong evidence that we should not take none of the above options I mentioned and have to take Jose's option. LOL

Because if we have an example like below, and we don't rename just use namespace to separate them. we will have a conflict when importing model A in both Modular and Classical layer as both op1 and op2 will end up in the same api file. 
```
@route("d")
interface D {
  op op1(@body body: B.A): void;
  @route("op2")
  op op2(@body body: A): void;
}
```

Though not sure if it's possible to refer the main namespace's model A in sub namespace B yet.

**Comment by MaryGao** [comment] 2023-10-24 05:57
>  Always build their name using their namespace hierarchy.

Not sure this is a good idea:
- This may introduce a lot of breakings changes in mgmt SDK
- According to my experience in mgmt if two schemas are with same names, usually we ask the customer why this happens, they would reply that they didn't realize these models are duplicated and these models are actually the exact the same so they will move to common place.
- Including the namespace would introduce breaking if customers move models from one place to another or refactor the namespace structure
- My assumption is that duplication may be not quite common, so general models would share the same namespace and the fact that every model has the same prefix like `AzureOpenAI` would be noisy for me.

I may prefer to have a option to turn off this behavior or only enable this for conflicts ones.

**Closed** 2023-11-04 01:13 UTC
Labels: HRLC, openai
