### ISSUE TITLE
recording the input swagger version or tag of code generation

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#842] opened 2021-01-21 03:25 UTC
Sometimes it's not very easy for us to figure out what kind versions or tags is the current SDK being generated from.  It would be nice if the code generator can add those information in the generated code. 
Which can be helpful if we want to do some general non RP-related upgrades on the SDKs, such as library dependencies upgrade etc.

**Comment by qiaozha** [comment] 2021-01-21 03:26
@ramya-rao-a

**Comment by sarangan12** [comment] 2021-02-11 06:00
@qiaozha Thanks for raising this issue. It is always good to record several details related to the generation such as:

1. swagger version/commit id
2. tag used
3. autorest version
4. SDK Generator Version
5. Modeler Four Version
6. Full Generation Command, etc.

The problem is that our SDK generation mechanism is slightly complicated for the SDK generators to record this information. **Why?** All the above information is passed to the Autorest Core. Autorest Core uses all this information and creates a CodeModel object which is then passed to individual language generators (C#, Java, TS, etc.) which uses the code model to generate the SDK. 

As you can see, all the listed information is stripped by the Autorest core and is not included in the codemodel. So, the language generators cannot record this information. So, if you want this information, then I would recommend creating the issue with the autorest repository at https://github.com/Azure/autorest. 

In the meantime, I recommend a best practice that would help you record the same information. For any SDK, I recommend creating a swagger folder which contains a README.md. This file must have all the required information. One of the sample files can be found at https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/search/search-documents/swagger/Service.md.

Then you can use the generation command as:

```
autorest --typescript swagger\Service.md
```

In this way, you regenerate your SDK only through this file and all the relevant information is always stored in this file and can be found easily. 

Please let me know if this solves your problem

**Comment by qiaozha** [comment] 2021-02-17 03:00
@sarangan12 Thanks for the detailed information. Actually you can pass an empty string to getValue. such as session.getValue('') to get all the autorest configuration. and in that way, we can record anything we want. Not sure if it's the right way to use getValue like this, but it works.
I do think the README.md sample is a good one for our recording result. it contains everything we need to regenerate the SDK. and we can also modify it per our requirements such as code generator upgrade etc.

**Comment by sarangan12** [comment] 2021-02-18 03:55
Thanks @qiaozha for the tip on the session.getValue(''). It was new to me. But, I did verify that object with a debugger. That object is very complicated and also varies depending on the input provided. I think the correct solution is to form a fixed object and send it to generators. Such an object could be designed only by the autorest core. I have created an issue with autorest at https://github.com/Azure/autorest/issues/3891.  

Until that issue is resolved, Please follow the best practice of documenting the details using the readme file. 

As there are no more pending action items on this issue, I am closing this now.

**Closed by sarangan12** 2021-02-18 03:55 UTC
