### ISSUE TITLE
[RLC] How to support to rename property

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#1751] opened 2023-02-10 07:47 UTC
## Background

In RLC we have no mapper layer between the client model and JSON model so the model property would be direct the underlying JSON property name. And we don't do any normalization for property. Thus the naming convention for generated code style is various and depends on the inputted Cadl.

Sometimes it uses the `_` style:

https://github.com/MaryGao/azure-sdk-for-js/blob/4bf35de4feb976261d60bb16830b7c66d03e3390/sdk/openai/openai-inference-rest/src/models.ts#L6-L10

Sometimes it uses camel style:

https://github.com/Azure/azure-sdk-for-js/blob/3e7fbf7634111dcb417df7cb7ef3a8e06d3c9bb0/sdk/anomalydetector/ai-anomaly-detector-rest/src/models.ts#L34-L41

## Question

I was wondering if we could have the mapper layer in RLC so we could normalize our code style OR next time we could have the ability to adjust our property name when the archs think the name is not proper.

**Comment by joheredi** [comment] 2023-02-14 23:51
We can't rename properties in RLC as there is no runtime mapping to keep track of the wire vs client side names. This is out of the scope of RLC and by design.

We'll address this in HRLC

**Comment by MaryGao** [comment] 2023-02-15 01:49
@lirenhe Do you have any concern for this? If no I will close this issue.

**Comment by lirenhe** [comment] 2023-02-15 05:19
json.stringify and json.parser all support the callback to customize the output, but I agree this is out of the scope for RLC.
Good to see this issue will be addressed in HRLC and @MaryGao, feel free to close this issue.

**Closed** 2023-02-16 00:20 UTC
Labels: needs-design
