### ISSUE TITLE
Interface OperationHeaders and PagingOperaitonNextResponse is generated in HLC but not modular

### ISSUE THREAD

**Issue by kazrael2119** [Azure/autorest.typescript#2384] opened 2024-03-26 06:40 UTC
in hlc, we have interface XXXHeaders in models.
for example:
in sphere, ProductsUpdateHeaders is defined in [models/index](https://github.com/kazrael2119/azure-sdk-for-js/blob/029a49c1573be8538a19745587a0cf5019b5e8a8/sdk/sphere/arm-sphere/src/models/index.ts#L657)
but it is not referenced to any place.
in modular, remove this and use XXX{status}Headers instead in [responses.ts](https://github.com/kazrael2119/azure-sdk-for-js/blob/40c582128de3ba0702763ddf3383333c0068078e/sdk/sphere/arm-sphere/src/rest/responses.ts#L894):
and there's a model named XXX{status}Response [use this header model](https://github.com/kazrael2119/azure-sdk-for-js/blob/40c582128de3ba0702763ddf3383333c0068078e/sdk/sphere/arm-sphere/src/rest/responses.ts#L904)

And in hlc, it will use XXXNextResponse as the response when the operation has next function: 
https://github.com/kazrael2119/azure-sdk-for-js/blob/029a49c1573be8538a19745587a0cf5019b5e8a8/sdk/sphere/arm-sphere/src/operations/operations.ts#L109-L110
and the definition of XXXNextResponse is :
https://github.com/kazrael2119/azure-sdk-for-js/blob/029a49c1573be8538a19745587a0cf5019b5e8a8/sdk/sphere/arm-sphere/src/models/index.ts#L1047
but not in modular

**Comment by joheredi** [comment] 2024-05-21 18:29
Is this causing an issue or we are just highlighting differences?

I'm not really worried about this change if it is not causing a problem with behavior. I don't expect customers to import 

I'd be okay closing this issue as "by design"

@qiaozha  if you agree, can you close this issue please?

**Comment by qiaozha** [comment] 2024-05-22 01:56
@kazrael2119 I think you are comparing the HLC with RLC ?

**Comment by joheredi** [comment] 2024-05-22 21:48
I think this is probably the same underlying issue as https://github.com/Azure/autorest.typescript/issues/2360 where response headers are ignored in Modular

**Comment by MaryGao** [comment] 2024-05-23 01:33
Yeah this is comparation between HLC and modular and maybe we could close this one considering these headers would wrap in issue https://github.com/Azure/autorest.typescript/issues/2360.

**Comment by MaryGao** [comment] 2024-05-23 02:16
@qiaozha @joheredi I will close this with above reason, let me know if any concern!

**Closed by MaryGao** 2024-05-23 02:16 UTC
Labels: P1, HRLC

**Comment by qiaozha** [comment] 2024-05-23 02:20
My concern here is about the next operations. do we have internal listNext in our new paging design?

**Comment by MaryGao** [comment] 2024-05-23 02:31
Personally I prefer to accept this breaking it is more like a bug in HLC to expose the interface `PagingOperaitonNextResponse` which is only used internally.

**Long story**
We will build an internal _listNext for paging operation and its response type would be exposed to public as PagingOperaitonNextResponse. https://github.com/kazrael2119/azure-sdk-for-js/blob/029a49c1573be8538a19745587a0cf5019b5e8a8/sdk/sphere/arm-sphere/src/models/index.ts#L1047

In modular we re-design paging without _listNext method now, so it would happen for breaking with interface `PagingOperaitonNextResponse`.

**Comment by qiaozha** [comment] 2024-05-23 02:45
I am okay to accept this, previously, I have some discussion with @xirzec about to not consider the changes of NextOptionalParams as breaking because it was internally used. but I am thinking we should consider this issue https://github.com/Azure/autorest.typescript/issues/1698 before the preview to avoid unnecessary breaking.

**Comment by kazrael2119** [comment] 2025-07-02 05:43
xxxNextOptionalParams, xxxResult and xxxResponse would be break by this
