### ISSUE TITLE
Add payload json merge patch 

### ISSUE THREAD

**Issue by v-jiaodi** [Azure/autorest.typescript#2272] opened 2024-02-02 01:09 UTC
**rlc case issue:**

<img width="630" alt="image" src="https://github.com/Azure/autorest.typescript/assets/80496810/92dbea09-2ee8-4cde-96f8-f3a85846fb94">

**modular case issue:**

<img width="636" alt="image" src="https://github.com/Azure/autorest.typescript/assets/80496810/0a7a8197-fdea-4189-9fbc-2d986cb25b9c">

**Comment by dgetu** [comment] 2024-02-02 04:21
Duplicate of #2001, not sure which one we should close

**Comment by qiaozha** [comment] 2024-02-06 08:38
close this one as duplicate https://github.com/Azure/autorest.typescript/issues/2001

**Closed by qiaozha** 2024-02-06 08:38 UTC
