### ISSUE TITLE
Generated createClient method does not use all parameters for parameterized host

### ISSUE THREAD

**Issue by chrissmiller** [Azure/autorest.typescript#1615] opened 2022-10-18 14:22 UTC
When using a parameterized host with multiple parts, the TS autorest client will only include parameters in the createClient method for one of the parts.

This impacts the PR and linked spec [here](https://github.com/Azure/azure-sdk-for-js/pull/23429/).

Our parameterized host looks like the following:

"{tenantId}-{resourceName}.{dnsSuffix}".

The expected createClient method would looks like the following:
```
export default function createClient(
  tenantId: string,
  devCenter: string,
  credentials: TokenCredential,
  devCenterDnsSuffix: string = "devcenter.azure.com",
  options: ClientOptions = {}
): AzureDevCenterClient {
  const baseUrl = options.baseUrl ?? `https://${tenantId}-${devCenter}.${devCenterDnsSuffix}`;
```
The actual method is as follows:
```
export default function createClient(
  tenantId: string,
  credentials: TokenCredential,
  options: ClientOptions = {}
): AzureDevCenterClient {
  const baseUrl = options.baseUrl ?? `https://${tenantId}-{devCenter}.{devCenterDnsSuffix}`;
```

autorest.typescript version is 6.0.0-rc.1

This generates an unusable createClient method, blocking use of the package. Happy to help investigate or provide more info as needed!

**Comment by MaryGao** [comment] 2022-10-18 14:50
@chrissmiller Thanks for reporting this! I believe we have already supported this [feature ](https://github.com/Azure/autorest.typescript/issues/1413)in our version since https://www.npmjs.com/package/@autorest/typescript/v/6.0.0-rc.2.

Would you like to have a try the latest one?

@qiaozha Please correct me if I am wrong! Thanks!

**Comment by chrissmiller** [comment] 2022-10-18 15:08
@MaryGao rc.2 fixes this issue for us, thank you so much! We are noticing a second issue withe the parameterized host in createClient though -- we have a default value for one of the host parameters, and the default value is not provided. We have manually fixed this for our PR, let me know if there is a fix we can consume instead though!

So rather than the expected output, we get:
```
export default function createClient(
  tenantId: string,
  devCenter: string,
  devCenterDnsSuffix: string,
  credentials: TokenCredential,
  options: ClientOptions = {}
): AzureDevCenterClient {
```

Link to the spec doc: https://github.com/Azure/azure-rest-api-specs/blob/75a8d8dcc9f6d0ec626bdeb32f5154f20c8c61cd/specification/devcenter/data-plane/Microsoft.DevCenter/preview/2022-03-01-preview/devcenter.json

**Comment by MaryGao** [comment] 2022-10-19 04:58
Generally we think the default value means that server side would autocomplete that value when missing so we don't handle them in client side. 

However I think your case is valid when parameters appear in extension `x-ms-parameterized-host`, these params would assemble in our url and usually are mandatory for client. So providing default values for them would benefit the user experience. 

So I think we could enhance them with default values.

@joheredi @qiaozha How do you think?

**Comment by sebrenna** [comment] 2022-11-03 18:18
@MaryGao thanks for the context. See you connected this with an issue, so does that mean you plan to fix the underlying issue at some point? Or do you still think this is by design?

**Comment by MaryGao** [comment] 2022-11-30 07:01
@sebrenna @chrissmiller We have implemented this in the latest codegen - https://www.npmjs.com/package/@autorest/typescript/v/6.0.0-rc.4. Feel free to have a try !

https://github.com/Azure/autorest.typescript/blob/c9bde370dcf8b2ef9caac6aa006121a8076a9d65/packages/cadl-rlc-test/test/anomalyDetector/cadl-output/src/anomalyDetector.ts#L8-L22

**Comment by MaryGao** [comment] 2022-11-30 07:03
Close this issue considering the issue resolved. Feel free to reopen it if necessary!

**Closed by MaryGao** 2022-11-30 07:03 UTC
Labels: customer-reported, needs-team-attention, Client, RLC, DPG/RLC Backlog
