### ISSUE TITLE
Issues with latest package

### ISSUE THREAD

**Issue by ffMathy** [Azure/autorest.typescript#1006] opened 2021-06-02 15:49 UTC
My Swagger JSON is as follows:

```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "General",
    "version": "v1"
  },
  "paths": {
    "/health": {
      "get": {
        "tags": [
          "General"
        ],
        "operationId": "healthGet",
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/api/sponsors/{beneficiaryId}": {
      "get": {
        "tags": [
          "General"
        ],
        "operationId": "api/sponsors/{beneficiaryId}Get",
        "parameters": [
          {
            "name": "beneficiaryId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Sponsorkit.Domain.Api.Sponsors.Beneficiary.Request"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/Sponsorkit.Domain.Api.Sponsors.Beneficiary.Request"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/Sponsorkit.Domain.Api.Sponsors.Beneficiary.Request"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/Sponsorkit.Domain.Api.Sponsors.Beneficiary.Response"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Sponsorkit.Domain.Api.Sponsors.Beneficiary.Response"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/Sponsorkit.Domain.Api.Sponsors.Beneficiary.Response"
                }
              }
            }
          }
        }
      }
    },
    "/api/sponsors/{beneficiaryId}/{reference}": {
      "post": {
        "tags": [
          "General"
        ],
        "operationId": "api/sponsors/{beneficiaryId}/{reference}Post",
        "parameters": [
          {
            "name": "beneficiaryId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "reference",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Sponsorkit.Domain.Api.Sponsors.BeneficiaryIdReference.Post.Request"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/Sponsorkit.Domain.Api.Sponsors.BeneficiaryIdReference.Post.Request"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/Sponsorkit.Domain.Api.Sponsors.BeneficiaryIdReference.Post.Request"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      },
      "get": {
        "tags": [
          "General"
        ],
        "operationId": "api/sponsors/{beneficiaryId}/{reference}Get",
        "parameters": [
          {
            "name": "beneficiaryId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "reference",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Sponsorkit.Domain.Api.Sponsors.BeneficiaryIdReference.Get.Request"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/Sponsorkit.Domain.Api.Sponsors.BeneficiaryIdReference.Get.Request"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/Sponsorkit.Domain.Api.Sponsors.BeneficiaryIdReference.Get.Request"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/Sponsorkit.Domain.Api.Sponsors.BeneficiaryIdReference.Get.Response"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Sponsorkit.Domain.Api.Sponsors.BeneficiaryIdReference.Get.Response"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/Sponsorkit.Domain.Api.Sponsors.BeneficiaryIdReference.Get.Response"
                }
              }
            }
          }
        }
      }
    },
    "/api/signup/from-github": {
      "post": {
        "tags": [
          "General"
        ],
        "operationId": "api/signup/from-githubPost",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Sponsorkit.Domain.Api.Signup.FromGitHub.Request"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/Sponsorkit.Domain.Api.Signup.FromGitHub.Request"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/Sponsorkit.Domain.Api.Signup.FromGitHub.Request"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/Sponsorkit.Domain.Api.Signup.FromGitHub.Response"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Sponsorkit.Domain.Api.Signup.FromGitHub.Response"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/Sponsorkit.Domain.Api.Signup.FromGitHub.Response"
                }
              }
            }
          }
        }
      }
    },
    "/api/signup/as-beneficiary": {
      "post": {
        "tags": [
          "General"
        ],
        "operationId": "api/signup/as-beneficiaryPost",
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/api/signup/activate-stripe-account/{userId}": {
      "get": {
        "tags": [
          "General"
        ],
        "operationId": "api/signup/activate-stripe-account/{userId}Get",
        "parameters": [
          {
            "name": "userId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Sponsorkit.Domain.Api.Signup.ActivateStripeAccountUserId.Request"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/Sponsorkit.Domain.Api.Signup.ActivateStripeAccountUserId.Request"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/Sponsorkit.Domain.Api.Signup.ActivateStripeAccountUserId.Request"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/api/browser/{beneficiaryId}/{reference}": {
      "get": {
        "tags": [
          "General"
        ],
        "operationId": "api/browser/{beneficiaryId}/{reference}Get",
        "parameters": [
          {
            "name": "beneficiaryId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "reference",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Sponsorkit.Domain.Api.Browser.BeneficiaryIdReference.Request"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/Sponsorkit.Domain.Api.Browser.BeneficiaryIdReference.Request"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/Sponsorkit.Domain.Api.Browser.BeneficiaryIdReference.Request"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Sponsorkit.Domain.Api.Browser.BeneficiaryIdReference.Request": {
        "type": "object",
        "properties": {
          "beneficiaryId": {
            "type": "string",
            "format": "uuid"
          },
          "reference": {
            "type": "string"
          }
        },
        "additionalProperties": false
      },
      "Sponsorkit.Domain.Api.Signup.ActivateStripeAccountUserId.Request": {
        "type": "object",
        "properties": {
          "userId": {
            "type": "string",
            "format": "uuid"
          }
        },
        "additionalProperties": false
      },
      "Sponsorkit.Domain.Api.Signup.FromGitHub.Request": {
        "type": "object",
        "properties": {
          "gitHubAuthenticationCode": {
            "type": "string"
          }
        },
        "additionalProperties": false
      },
      "Sponsorkit.Domain.Api.Signup.FromGitHub.Response": {
        "type": "object",
        "properties": {
          "token": {
            "type": "string"
          }
        },
        "additionalProperties": false
      },
      "Sponsorkit.Domain.Api.Sponsors.Beneficiary.Request": {
        "type": "object",
        "properties": {
          "beneficiaryId": {
            "type": "string",
            "format": "uuid"
          }
        },
        "additionalProperties": false
      },
      "Sponsorkit.Domain.Api.Sponsors.Beneficiary.Response": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "format": "uuid"
          },
          "gitHubId": {
            "type": "integer",
            "format": "int64",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "Sponsorkit.Domain.Api.Sponsors.BeneficiaryIdReference.Get.Models.DonationsResponse": {
        "type": "object",
        "properties": {
          "totalInHundreds": {
            "type": "integer",
            "format": "int32",
            "readOnly": true
          },
          "monthlyInHundreds": {
            "type": "integer",
            "format": "int32",
            "readOnly": true
          }
        },
        "additionalProperties": false
      },
      "Sponsorkit.Domain.Api.Sponsors.BeneficiaryIdReference.Get.Models.Sponsor.SponsorResponse": {
        "type": "object",
        "properties": {
          "monthlyAmountInHundreds": {
            "type": "integer",
            "format": "int32",
            "nullable": true,
            "readOnly": true
          },
          "totalAmountInHundreds": {
            "type": "integer",
            "format": "int32",
            "readOnly": true
          },
          "startedAtUtc": {
            "type": "string",
            "format": "date-time",
            "readOnly": true
          }
        },
        "additionalProperties": false
      },
      "Sponsorkit.Domain.Api.Sponsors.BeneficiaryIdReference.Get.Models.Sponsor.SponsorsByAmountResponse": {
        "type": "object",
        "properties": {
          "most": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Sponsorkit.Domain.Api.Sponsors.BeneficiaryIdReference.Get.Models.Sponsor.SponsorResponse"
            },
            "readOnly": true
          },
          "least": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Sponsorkit.Domain.Api.Sponsors.BeneficiaryIdReference.Get.Models.Sponsor.SponsorResponse"
            },
            "readOnly": true
          }
        },
        "additionalProperties": false
      },
      "Sponsorkit.Domain.Api.Sponsors.BeneficiaryIdReference.Get.Models.Sponsor.SponsorsByDateResponse": {
        "type": "object",
        "properties": {
          "latest": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Sponsorkit.Domain.Api.Sponsors.BeneficiaryIdReference.Get.Models.Sponsor.SponsorResponse"
            },
            "readOnly": true
          },
          "oldest": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Sponsorkit.Domain.Api.Sponsors.BeneficiaryIdReference.Get.Models.Sponsor.SponsorResponse"
            },
            "readOnly": true
          }
        },
        "additionalProperties": false
      },
      "Sponsorkit.Domain.Api.Sponsors.BeneficiaryIdReference.Get.Models.Sponsor.SponsorsResponse": {
        "type": "object",
        "properties": {
          "current": {
            "$ref": "#/components/schemas/Sponsorkit.Domain.Api.Sponsors.BeneficiaryIdReference.Get.Models.Sponsor.SponsorResponse"
          },
          "byAmount": {
            "$ref": "#/components/schemas/Sponsorkit.Domain.Api.Sponsors.BeneficiaryIdReference.Get.Models.Sponsor.SponsorsByAmountResponse"
          },
          "byDate": {
            "$ref": "#/components/schemas/Sponsorkit.Domain.Api.Sponsors.BeneficiaryIdReference.Get.Models.Sponsor.SponsorsByDateResponse"
          }
        },
        "additionalProperties": false
      },
      "Sponsorkit.Domain.Api.Sponsors.BeneficiaryIdReference.Get.Request": {
        "type": "object",
        "properties": {
          "beneficiaryId": {
            "type": "string",
            "format": "uuid"
          },
          "reference": {
            "type": "string"
          }
        },
        "additionalProperties": false
      },
      "Sponsorkit.Domain.Api.Sponsors.BeneficiaryIdReference.Get.Response": {
        "type": "object",
        "properties": {
          "donations": {
            "$ref": "#/components/schemas/Sponsorkit.Domain.Api.Sponsors.BeneficiaryIdReference.Get.Models.DonationsResponse"
          },
          "sponsors": {
            "$ref": "#/components/schemas/Sponsorkit.Domain.Api.Sponsors.BeneficiaryIdReference.Get.Models.Sponsor.SponsorsResponse"
          }
        },
        "additionalProperties": false
      },
      "Sponsorkit.Domain.Api.Sponsors.BeneficiaryIdReference.Post.Request": {
        "type": "object",
        "properties": {
          "beneficiaryId": {
            "type": "string",
            "format": "uuid"
          },
          "reference": {
            "type": "string"
          },
          "amountInHundreds": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          },
          "email": {
            "type": "string",
            "nullable": true
          },
          "stripeCardId": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      }
    }
  }
}
```

Now, I am generating my client with the following command-line:

```bash
autorest --reset && autorest --clear-output-folder --use-core-v2 --package-name=@sponsorkit/client --v3 --markOpenAPI3ErrorsAsWarning --typescript --input-file=http://localhost:5000/swagger/v1/swagger.json --output-folder=./src/api/openapi && cd ./src/api/openapi && npm i && npm run build
```

But when I try to use it, with the code:

```typescript
import { General } from "./openapi/src/general";

export const apiClient = new General(
{
    getToken: async () => ({token: "dummy", expiresOnTimestamp: 13371337})
},
"");
```

Then I get the error:

![image](https://user-images.githubusercontent.com/2824010/120511579-d3411500-c3ca-11eb-8124-723365af5872.png)

**Comment by ramya-rao-a** [comment] 2021-06-02 22:55
Thanks for reporting @ffMathy 

@sarangan12 Can you please take a look?

**Comment by sarangan12** [comment] 2021-06-03 06:05
It is the same as the issue reported in https://github.com/Azure/autorest.typescript/issues/1004. I am able to reproduce the issue locally. 

Now, when I use the same test file `within` the V6 SDK Generator package as one of the integration test case, I do not get this error. It works fine.

But, when I use the released `@autorest/typescript` package and then use it for the same swagger, I get this error. Now, the problem is not with the code itself (if so, it will occur in both cases). I suspect, that the way it is compiled (setting the target, moduleresolution, etc) is the one thats causing the problem. 

I have not found a solution yet for this problem. I will update this issue once I have a solution.

**Comment by ffMathy** [comment] 2021-06-03 06:21
Wow you guys impress me with your low response times and professionalism around this. Keep it up! 😍

**Comment by ffMathy** [comment] 2021-06-03 06:22
I should note that despite saying it's for the latest package, I don't actually know if it's only the latest package, or if it affects other builds too.

**Comment by sarangan12** [comment] 2021-06-08 04:39
@ffMathy I have analyzed the issue and found the root cause of the issue. A detailed explanation and a temporary workaround has been provided at https://github.com/Azure/autorest.typescript/issues/1004#issuecomment-856387723.

Once a permanent solution has been decided upon and implemented, I will provide the update in https://github.com/Azure/autorest.typescript/issues/1004. For now, you could follow the workaround to unblock yourself. 

For now, I am closing this issue. You can track the progress of this issue at https://github.com/Azure/autorest.typescript/issues/1004.

**Closed by sarangan12** 2021-06-08 04:39 UTC
Labels: customer-reported, question
