### ISSUE TITLE
Do we prompt shared apiVersion param in operation level to client level?

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#2337] opened 2024-03-07 13:30 UTC
Currently we only generate client level apiVerison if it is defined in path parameter in RLC, I was wondering if we need to prompt apiVersion in operation level to client level if all operations share the same apiVersion ?

**Comment by qiaozha** [comment] 2024-03-08 11:48
I don't think we need a new issue for this https://github.com/Azure/autorest.typescript/issues/2148

**Comment by lirenhe** [comment] 2024-08-15 08:57
close it as duplicate of https://github.com/Azure/autorest.typescript/issues/2148

**Closed by lirenhe** 2024-08-15 08:57 UTC
Labels: P1, RLC, HRLC
