### ISSUE TITLE
TS4022 Using RequestOptionsBase

### ISSUE THREAD

**Issue by chieftn** [Azure/autorest.typescript#77] opened 2018-05-10 23:19 UTC
autorest output of  file [https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/iothub/resource-manager/Microsoft.Devices/stable/2018-04-01/iothub.json](url) with following specifications:

typescript.azure-arm: true
typescript:
    output-folder: ./lib/
license-header: MICROSOFT_MIT_NO_VERSION
add-credentials: true
package-name: microsoft-azure-devices-iothub-controlplane
input-file: ./src/2018-04-01/iothub.json
package-version: 2018.04.01.01
generate-metadata: true

fails on tsc.  "Receiving TS4022 --  has or is using private name 'RequestOptionsBase'."  Manually corrected by exporting type RequestOptionsBase.  Looking to understand if this is user error and / or correctable.  

Loading AutoRest core      'C:\Users\rkessler\.autorest\@microsoft.azure_autorest-core@2.0.4277\node_modules\@microsoft.azure\autorest-core\dist' (2.0.4277)
   Loading AutoRest extension '@microsoft.azure/autorest.typescript' (~2.0.12->2.0.176)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.1.23->2.1.23)

New to tech -- so guidance appreciated.

**Comment by RikkiGibson** [comment] 2018-05-24 21:34
Did this have a similar root cause as #76? Was it resolved by installing preview versions of autorest.typescript and ms-rest-js?

Please feel free to reopen if this is still a problem.

**Closed by RikkiGibson** 2018-05-24 21:34 UTC

**Comment by trusktr** [comment] 2019-12-21 20:28
I've opened a request to fix issues like these in TypeScript by bringing declaration files to parity with language features. https://github.com/microsoft/TypeScript/issues/35822
