### ISSUE TITLE
building typescript client with docker-all fails

### ISSUE THREAD

**Issue by checkin247** [Azure/autorest.typescript#1731] opened 2023-01-22 21:52 UTC
I have been using the docker image "azuresdk/autorest" to build the typescript autorest client,

Since recently, I get the error:

```
 | error: @apidevtools/json-schema-ref-parser@9.1.1: The engine "node" is incompatible with this module. Expected version ">= 17". Got "14.19.1"
  | error: Found incompatible module.
```

Docker usage instructions for autorest found here:
https://github.com/Azure/autorest/blob/main/docs/docker.md
Image used: https://hub.docker.com/r/azuresdk/autorest
The image was not updated in the past months. Is that the correct container repository?

Building the image manually also fails with:
````
#5 2.840 Err:13 http://security.ubuntu.com/ubuntu impish-security Release
#5 2.840   404  Not Found
````

Seems the docker image node version needs to be updated.

**Comment by HangyiWang** [comment] 2023-01-23 20:14
Hi, same error here. 

We're using `autorest/typescript` extension to build our API clients and recently `autorest autorest.md` always failed due to this breaking change from `@apidevtools/json-schema-ref-parser@9.1.1`. We were trying to fix the `json-shcema-ref-parser` version in our project NPM package.json but it's not working since it's nested dependency in the autorest extension installed using YARN.

We believe the issue is caused by this breaking change: https://github.com/APIDevTools/json-schema-ref-parser/issues/298 

Since this issue is heavily affect our building pipeline these days, anything we can do to mitigate/resolve this ASAP? Thanks.

**Comment by HangyiWang** [comment] 2023-01-23 20:40
Currently we're using `6.0.0-rc.1` and we're changing back to `6.0.0-beta.15` for temporary mitigation since it doesn't depend on that parser.

**Comment by checkin247** [comment] 2023-01-23 22:22
@HangyiWang you may want to try this [autorest-npm](https://hub.docker.com/r/checkin247/autorest-npm) image.
I am using it in a pipeline as a replacement of the "autrest-all".

**Comment by HangyiWang** [comment] 2023-01-23 22:27
Thanks @checkin247 . But we're using autorest as NPM dependency not image.

**Comment by HangyiWang** [comment] 2023-01-23 22:37
@checkin247 Sorry for adding those context in your issue. This is the question for the autorest team. Thanks for the help btw! 😄

**Comment by MaryGao** [comment] 2023-05-17 04:13
Close it as not autorest.typescript issue

**Closed by MaryGao** 2023-05-17 04:13 UTC
Labels: question, customer-reported
