### ISSUE TITLE
Build problem on Hello World

### ISSUE THREAD

**Issue by ThomasArdal** [Azure/autorest.typescript#142] opened 2018-06-04 19:07 UTC
I've tried following the description in the readme to generate and build a simple project. I end up with compile errors as shown in the end of this issue.

I'm using AutoRest version 2.0.4262 and node version 8.11.2.

Then generating the client:

```
autorest --typescript --output-folder=lib --input-file=http://petstore.swagger.io/v2/swagger.json --package-name=test --package-version=1.0.0 --add-credentials=true --generate-metadata=true
```

Client is successfully generated in the lib folder.

```
npm install
npm install -g gulp
```

Success!

```
npm run build
```

Results in the following errors:

```
> test@1.0.0 build C:\projects\autorest-javascript-example
> npm -s run-script tsc && webpack && node node_modules/uglify-es/bin/uglifyjs --source-map -c -m -o swaggerPetstoreBundle.min.js swaggerPetstoreBundle.js

lib/swaggerPetstore.ts:95:5 - error TS2322: Type '{}' is not assignable to type 'HttpHeaders'.
  Property '_headersMap' is missing in type '{}'.

95     httpRequest.headers = {};
       ~~~~~~~~~~~~~~~~~~~


lib/swaggerPetstore.ts:97:5 - error TS7017: Element implicitly has an 'any' type because type 'HttpHeaders' has no index signature.

97     httpRequest.headers['Content-Type'] = 'application/json; charset=utf-8';
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


lib/swaggerPetstore.ts:101:11 - error TS7017: Element implicitly has an 'any' type because type 'HttpHeaders' has no index signature.

101           httpRequest.headers[headerName] = options.customHeaders[headerName];
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

...

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! test@1.0.0 build: `npm -s run-script tsc && webpack && node node_modules/uglify-es/bin/uglifyjs --source-map -c -m -o swaggerPetstoreBundle.min.js swaggerPetstoreBundle.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the test@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\thoma\AppData\Roaming\npm-cache\_logs\2018-06-04T19_00_54_025Z-debug.log
```

What could be wrong here?

**Comment by daschult** [comment] 2018-06-04 19:44
We're sorry that you've been having issues with the AutoRest.TypeScript generator. We've been changing a few things and still working out our release process, but I think we've got it working now so you shouldn't see as many of these kinds of issues going forward. If you regenerate now, everything should work fine.

**Comment by ThomasArdal** [comment] 2018-06-04 19:56
@daschult So, there's a new release after your current sprint?

**Comment by daschult** [comment] 2018-06-04 19:59
We haven't finalized on how often we're going to promote the latest preview version to latest. A new preview version is created automatically whenever we merge changes to our runtime or generator, but the process of promoting a preview version to latest is still manual.
So, to answer you're question, we're not sure yet. The latest version of the generator and runtime should always be compatible from now on, however.

**Comment by daschult** [comment] 2018-06-04 20:00
Were you able to generator working code with the latest versions?

**Comment by ThomasArdal** [comment] 2018-06-04 20:03
The latest version is 2.0.4262, right? That's the version that causes the compile errors.

**Comment by ThomasArdal** [comment] 2018-06-04 20:10
I ran the following commands and still see the errors:

```
autorest --version=latest
npm install -g @microsoft.azure/autorest.typescript
```

**Comment by daschult** [comment] 2018-06-04 20:11
AutoRest is a complicated beast. That's the version of the core AutoRest application. The AutoRest.TypeScript plugin (which you invoke by adding `--typescript` to your command) is a completely separate NPM package with a separate version. You can see which version of the TypeScript generator you're using by running `autorest --typescript`.

```cmd
C:\Users\daschult> autorest --typescript
AutoRest code generation utility [version: 2.0.4262; node: v9.7.1]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\daschult\.autorest\@microsoft.azure_autorest-core@2.0.4279\node_modules\@microsoft.azure\autorest-core\dist' (2.0.4279)
   Loading AutoRest extension '@microsoft.azure/autorest.typescript' (~2.0.12->2.0.304)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.1.23->2.1.23)
[Exception] No input files provided.

Use --help to get help information.
```
If you don't see 2.0.304 at the end of the `@microsoft.azure/autorest.typescript` line, then reset autorest by running the following command:
```cmd
C:\Users\daschult>autorest --reset
AutoRest code generation utility [version: 2.0.4262; node: v9.7.1]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
C:\Users\daschult\.autorest\@microsoft.azure_autorest-core@2.0.4279\autorest-core -> C:\Users\daschult\.autorest\@microsoft.azure_autorest-core@2.0.4279\node_modules\@microsoft.azure\autorest-core\dist\app.js
C:\Users\daschult\.autorest\@microsoft.azure_autorest-core@2.0.4279\autorest-language-service -> C:\Users\daschult\.autorest\@microsoft.azure_autorest-core@2.0.4279\node_modules\@microsoft.azure\autorest-core\dist\language-service\language-service.js
   Loading AutoRest core      'C:\Users\daschult\.autorest\@microsoft.azure_autorest-core@2.0.4279\node_modules\@microsoft.azure\autorest-core\dist' (2.0.4279)
```
Then when you run `autorest --typescript` you should see the version number update.

**Comment by ThomasArdal** [comment] 2018-06-04 20:23
Thanks! That definitely did something. Now, when running, I see the following:

```
C:\projects\autorest-javascript-example>autorest --typescript
AutoRest code generation utility [version: 2.0.4262; node: v8.11.2]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\thoma\.autorest\@microsoft.azure_autorest-core@2.0.4279\node_modules\@microsoft.azure\autorest-core\dist' (2.0.4279)
   Loading AutoRest extension '@microsoft.azure/autorest.typescript' (~2.0.12->2.0.304)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.1.23->2.1.23)
[Exception] No input files provided.

Use --help to get help information.
```

Looks like the correct version now. Result in some new compile errors:

```
C:\projects\autorest-javascript-example>npm run build

> test@1.0.0 build C:\projects\autorest-javascript-example
> npm -s run-script tsc && webpack && node node_modules/uglify-es/bin/uglifyjs --source-map -c -m -o swaggerPetstoreBundle.min.js swaggerPetstoreBundle.js

lib/swaggerPetstore.ts:204:66 - error TS2694: Namespace '"C:/projects/autorest-javascript-example/lib/models/index"' has no exported member 'Enum'.

204   async findPetsByStatusWithHttpOperationResponse(status: Models.Enum[], options?: msRest.RequestOptionsBase): Promise<msRest.HttpOperationResponse<Models.Pet[]>> {
                                                                     ~~~~


lib/swaggerPetstore.ts:779:57 - error TS2339: Property 'isStream' does not exist on type 'typeof import("C:/projects/autorest-javascript-example/node_modules/ms-rest-js/typings/lib/msRest")'.

779       if (file !== null && file !== undefined && msRest.isStream(file)) {
                                                            ~~~~~~~~


lib/swaggerPetstore.ts:2072:35 - error TS2694: Namespace '"C:/projects/autorest-javascript-example/lib/models/index"' has no exported member 'Enum'.

2072   findPetsByStatus(status: Models.Enum[]): Promise<Models.Pet[]>;
                                       ~~~~


lib/swaggerPetstore.ts:2073:35 - error TS2694: Namespace '"C:/projects/autorest-javascript-example/lib/models/index"' has no exported member 'Enum'.

2073   findPetsByStatus(status: Models.Enum[], options: msRest.RequestOptionsBase): Promise<Models.Pet[]>;
                                       ~~~~


lib/swaggerPetstore.ts:2074:35 - error TS2694: Namespace '"C:/projects/autorest-javascript-example/lib/models/index"' has no exported member 'Enum'.

2074   findPetsByStatus(status: Models.Enum[], callback: msRest.ServiceCallback<Models.Pet[]>): void;
                                       ~~~~


lib/swaggerPetstore.ts:2075:35 - error TS2694: Namespace '"C:/projects/autorest-javascript-example/lib/models/index"' has no exported member 'Enum'.

2075   findPetsByStatus(status: Models.Enum[], options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.Pet[]>): void;
                                       ~~~~


lib/swaggerPetstore.ts:2076:35 - error TS2694: Namespace '"C:/projects/autorest-javascript-example/lib/models/index"' has no exported member 'Enum'.

2076   findPetsByStatus(status: Models.Enum[], options?: msRest.RequestOptionsBase, callback?: msRest.ServiceCallback<Models.Pet[]>): any {
                                       ~~~~


npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! test@1.0.0 build: `npm -s run-script tsc && webpack && node node_modules/uglify-es/bin/uglifyjs --source-map -c -m -o swaggerPetstoreBundle.min.js swaggerPetstoreBundle.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the test@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\thoma\AppData\Roaming\npm-cache\_logs\2018-06-04T20_23_33_263Z-debug.log
```

**Comment by daschult** [comment] 2018-06-04 20:36
Congratulations! You found the two bugs that we're actively dealing with right now.
1. **Enum** - The Enum bug is most likely caused by defining an `enum` property inside of a `parameter` section. You can try to work around this by extracting the `items` property of the parameter in your specification to a separate "definitions" section of your OpenAPI/Swagger specification file. This helps AutoRest to recognize the enumeration and to properly generate code for it.
2. msRest.isStream() - This is an issue that I have been personally working on lately. You can just delete the msRest.isStream() expression from your generated code for now, and I'll update this issue when I have a fix for it in preview.

**Comment by ThomasArdal** [comment] 2018-06-04 20:38
Great. Thank you for the details on that. Do you have issue numbers for those bugs, that I can follow?

**Comment by daschult** [comment] 2018-06-04 21:10
I just updated my prior comment with those issues, but here they are again:
Enum - https://github.com/Azure/autorest.typescript/issues/88
msRest.isStream() - https://github.com/Azure/autorest.typescript/issues/145

**Comment by ThomasArdal** [comment] 2018-06-04 21:17
Maybe we should close this issue?

**Comment by daschult** [comment] 2018-06-04 21:19
If you're satisfied, then I'll go ahead and close this issue.

**Closed by daschult** 2018-06-04 21:19 UTC
Labels: Started-Sprint-119, Unplanned-Sprint-119, customer-reported, in progress
