### ISSUE TITLE
multiple response code

### ISSUE THREAD

**Issue by KeXu444** [Azure/autorest.typescript#476] opened 2019-04-30 21:26 UTC
When multiple response used in swagger
Generated typescript package does not have strong typed response.

        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/ImageResponseBase"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/ModelErrorResponse"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "$ref": "#/definitions/ModelErrorResponse"
            }
          },
          "500": {
            "description": "Server Error"
          },
          "401": {
            "description": "Unauthorized"
          }
        }

**Comment by joheredi** [comment] 2020-01-14 21:57
This is a duplicate of #283 where we need to support `x-ms-error-response` extension in the new version of autorest.typescript

**Closed by joheredi** 2020-01-14 21:57 UTC
