### ISSUE TITLE
[HLC] can not set apiversion in method-level operation

### ISSUE THREAD

**Issue by kazrael2119** [Azure/autorest.typescript#1725] opened 2023-01-17 03:04 UTC
package:@azure/arm-operationalinsights
Package Version: "^8.0.1"
sdk issue:https://github.com/Azure/azure-sdk-for-js/issues/24369

By using the version provided in this sdk issue, I can reproduce his error. But I have no way to set method-level apiVersion. If I set my apiVersion with casting manually, it doesn't work
![image](https://user-images.githubusercontent.com/98569699/212800596-2afe66e1-17fd-414f-ad52-1bcd73364b5e.png)

![image](https://user-images.githubusercontent.com/98569699/212800605-7d434948-54d6-412b-823b-5ff0fc7c4c77.png)

**Comment by MaryGao** [comment] 2023-01-30 09:00
Confirmed with qiaoqiao, this is by design so I'll close this issue.

**Closed by MaryGao** 2023-01-30 09:00 UTC
