### ISSUE TITLE
Error: modelProperties cannot be null or undefined in the mapper

### ISSUE THREAD

**Issue by ffMathy** [Azure/autorest.typescript#1175] opened 2021-08-26 10:37 UTC
I am getting the following error. I am on the latest version.

> Error: modelProperties cannot be null or undefined in the mapper "{"type":{"name":"Composite","className":"ApiTransactionResponseUpdatesItem"}}" of type "ApiTransactionResponseUpdatesItem" for object "operationRes.parsedBody.updates[0]". occurred in deserializing the responseBody - {"updates":[{"timeUtc":"2021-08-26T10:27:09.334Z","type":"declined"}]}

Any idea on how to solve this?

**Comment by sarangan12** [comment] 2021-08-28 02:22
@ffMathy Could you please share the swagger/snippet of the swagger that you are using that is causing this error?

**Comment by ffMathy** [comment] 2021-08-30 06:44
It is this: https://app.reshopper.com/swagger/v1/swagger.json

**Comment by ffMathy** [comment] 2021-09-07 10:28
@sarangan12 is the information provided sufficient?

**Comment by sarangan12** [comment] 2021-09-07 18:07
@ffMathy Thanks. Yes. That is the information I need. If I need any more information, I will update the issue. I am still working on the issue.

**Comment by ffMathy** [comment] 2021-09-07 18:26
Ah perfect then 🙏

Sorry, I was unsure if you had seen the message. Great to hear you are already working on it! You guys are awesome!

**Comment by sarangan12** [comment] 2021-09-07 22:22
Hi @ffMathy 

I have used the following command(with the latest version of the generator):

```
autorest.cmd --typescript --use-core-v2=true --title=SwaggerClient --allow-insecure-connection=true --is-test-package=true --license-header=false --add-credentials=false --package-version=1.0.0-preview1 --input-file=test/integration/swaggers/swagger.json --clear-output-folder=true --output-folder=./test/integration/generated/swagger --use=@autorest/typescript@6.0.0-beta.12 --package-name=swagger
```

I was able to  generate the SDK and build it without any errors. Could you please tell me the command, version that you use? Also, in which step are you getting the error, generation/build? 

Could you please try it with the latest version of the generator?

**Comment by sarangan12** [comment] 2021-09-14 18:14
Closing this issue for now. If you still face this issue, feel free to reopen this issue.

**Comment by ffMathy** [comment] 2021-09-14 20:32
Did you try with my swagger file, the one I sent? Still getting an error with the same command-line. Sorry, didn't see your original message, but please re-open :pray:

**Comment by sarangan12** [comment] 2021-09-14 20:48
Reopening based on the comments from @ffMathy

**Comment by sarangan12** [comment] 2021-09-14 20:50
@ffMathy Yes. I have tried with the same swagger file that you have sent. Did you use the command that I have provided? Which step gives you error? Is it during the generation? Or Is it during the build after the generation? (I do not receive errors in either steps)

**Comment by sarangan12** [comment] 2021-09-16 17:01
@ffMathy Could you please respond to my previous question?

**Comment by ffMathy** [comment] 2021-09-17 07:06
Ah well I should elaborate... It doesn't crash at compile-time. It crashes at runtime.

**Comment by sarangan12** [comment] 2021-09-17 17:17
@ffMathy Ok. Now it is clear. The SDK generation is fine. Build is fine. It happens during the runtime. 

1. Which API are you calling? 
2. What is the input to that API? 
3. What is the expected output?

I think the error is happening during the deserialization. So, what is the serialized input that you are sending? What is the Service expecting?  

Since this is an external API, I cannot debug it from my side. I need your input in moving forward.

**Comment by ffMathy** [comment] 2021-09-23 10:48
Wait, I updated from version 10 to 13, and now it seems to work.

Was this fixed in the meantime?

**Comment by ffMathy** [comment] 2021-11-01 08:56
@sarangan12 this is now happening again, but I think it has something to do with the data.

Here's the full error, including a data example:

```
Error Error: modelProperties cannot be null or undefined in the mapper "{"type":{"name":"Composite","className":"ApiTransactionResponseUpdatesItem"}}" of type "ApiTransactionResponseUpdatesItem" for object "operationRes.parsedBody.updates[0]". occurred in deserializing the responseBody - {"id":"617fa3aa57613c99b5b77e70","type":"cardshipping","stateEnum":"declined","state":"Declined","waitingFor":"Seller","buyer":{"userId":"5c5c39e94c9d4404d4577e94","publicName":"Mathias","firstName":"Mathias","lastName":"","profileImages":[{"url":"https://profiles-media-dev.reshopper.com/2021/05/04/de16aead-f1d2-4301-8e96-a8d07eb9269f/256x569.webp","fileId":"de16aead-f1d2-4301-8e96-a8d07eb9269f","width":256,"height":569,"blurHash":"K7Nmyd01?b?wD*oIIUxuxu","timeUploaded":"2021-05-04T12:02:47.824Z"},{"url":"https://profiles-media-dev.reshopper.com/2021/05/04/de16aead-f1d2-4301-8e96-a8d07eb9269f/1000x1000.webp","fileId":"de16aead-f1d2-4301-8e96-a8d07eb9269f","width":1000,"height":1000,"blurHash":"K7NmycM|-;?w01xts,?bM{","timeUploaded":"2021-05-04T12:02:47.929Z"}],"profilePictureUrl":"https://s3-eu-west-1.amazonaws.com/profiles-media-dev.reshopper.com/2021/05/04/de16aead-f1d2-4301-8e96-a8d07eb9269f/1000x1000.webp","lastSessionUtc":"2021-11-01T08:50:49.169Z","address":{"street":"Inge Lehmanns Gade 10","zipCode":"8000","city":"Aarhus C","country":"DK","location":{"long":10.2155391,"lon":10.2155391,"lat":56.1586902},"hideDetails":false},"plusUser":false,"businessInformation":{"type":"ngo","autoAcceptOffers":false,"allowItemComments":false,"allowOfferComments":false},"stats":{"itemsCreated":213,"firstItemCreated":"2019-02-11T10:53:08.285Z","tradingStatistic":{"purchase":{"shippingTransactionCount":{"count":18},"transactionCount":{"count":3},"individualTradeCount":{"count":2}},"sold":{"shippingTransactionCount":{"count":12},"transactionCount":{"count":4},"individualTradeCount":{"count":0}}}},"country":"DK"},"seller":{"userId":"5efde1f82d30860001f07cbb","publicName":"Jeppe B","firstName":"Jeppe","lastName":"B","profileImages":[{"url":"https://profiles-media-dev.reshopper.com/2021/04/05/2e479886-1331-40b6-9915-226c99b559f0/256x256.webp","fileId":"2e479886-1331-40b6-9915-226c99b559f0","width":256,"height":256,"timeUploaded":"2021-04-05T10:01:41.224Z"},{"url":"https://profiles-media-dev.reshopper.com/2021/04/05/2e479886-1331-40b6-9915-226c99b559f0/1078x1000.webp","fileId":"2e479886-1331-40b6-9915-226c99b559f0","width":1078,"height":1000,"timeUploaded":"2021-04-05T10:01:41.272Z"}],"profilePictureUrl":"https://s3-eu-west-1.amazonaws.com/profiles-media-dev.reshopper.com/2021/04/05/2e479886-1331-40b6-9915-226c99b559f0/256x256.webp","lastSessionUtc":"2021-10-19T08:39:22.324Z","address":{"street":"Christian IX's Vej 6","zipCode":"5230","city":"Odense M","country":"DK","location":{"long":10.3849805,"lon":10.3849805,"lat":55.3809096},"hideDetails":true},"plusUser":false,"stats":{"itemsCreated":83,"firstItemCreated":"2020-07-02T13:38:16.963Z","tradingStatistic":{"purchase":{"shippingTransactionCount":{"count":10},"transactionCount":{"count":3},"individualTradeCount":{"count":1}},"sold":{"shippingTransactionCount":{"count":7},"transactionCount":{"count":0},"individualTradeCount":{"count":2}}}},"country":"DK"},"updates":[{"timeUtc":"2021-11-01T08:54:25.665Z","type":"declined"}],"items":[{"id":"5f60a85c186038c98a09455d","brandOrTitle":"Hjemmelevering","description":"DAO Home","size":"92","picture":"https://items-media-dev.reshopper.com/2020/09/15/b0fe7be2-9b40-4ff5-8450-03d874171f60/256x256.webp","images":[{"url":"https://items-media-dev.reshopper.com/2020/09/15/b0fe7be2-9b40-4ff5-8450-03d874171f60/256x256.webp","fileId":"b0fe7be2-9b40-4ff5-8450-03d874171f60","width":256,"height":256,"blurHash":"KZKBK^WBRj0KRjxuD*-;tR","timeUploaded":"2020-09-15T11:40:53.462Z"},{"url":"https://items-media-dev.reshopper.com/2020/09/15/b0fe7be2-9b40-4ff5-8450-03d874171f60/1000x2000.webp","fileId":"b0fe7be2-9b40-4ff5-8450-03d874171f60","width":1000,"height":2000,"blurHash":"KEJRaJ~pIVOZIoWC56_3jI","timeUploaded":"2020-09-15T11:40:53.466Z"}],"priceInHundreds":20000,"available":false},{"id":"5f60a882186038c98a094f82","brandOrTitle":"Dollar","description":"Gg","age":"9","picture":"https://items-media-dev.reshopper.com/2020/09/15/f10c7cce-652a-4539-a0ef-41a6034d78b2/256x256.webp","images":[{"url":"https://items-media-dev.reshopper.com/2020/09/15/f10c7cce-652a-4539-a0ef-41a6034d78b2/256x256.webp","fileId":"f10c7cce-652a-4539-a0ef-41a6034d78b2","width":256,"height":256,"blurHash":"KTMa6J~V-Bx]R*NGD%WBkC","timeUploaded":"2020-09-15T11:41:29.986Z"},{"url":"https://items-media-dev.reshopper.com/2020/09/15/f10c7cce-652a-4539-a0ef-41a6034d78b2/1000x2000.webp","fileId":"f10c7cce-652a-4539-a0ef-41a6034d78b2","width":1000,"height":2000,"blurHash":"KILXDD~W^j?bWAIn9ZE1OE","timeUploaded":"2020-09-15T11:41:29.99Z"}],"priceInHundreds":5000,"available":false}],"bid":{"currency":"DKK","listingPrice":25000,"currentOffer":29000,"offerHistory":[{"offerUtc":"2021-11-01T08:22:02.75Z","amount":29000,"sender":"buyer"}],"split":{"feePercentage":0,"fee":0,"shipping":4000,"payout":0}},"details":{"payment":{"refundedAmountInHundreds":0},"shipping":{"pickupPointId":106253,"unit":"kilograms","weight":5,"status":"PRE_NOTIFIED","state":"preNotified","statusHistory":["PRE_NOTIFIED"],"isReadyForTracking":false,"type":"bring","existsInBringSystem":false,"handInBeforeUtc":"0001-01-01T00:00:00Z"}},"ttlUtc":"2021-11-02T08:54:25.747Z","createdUtc":"2021-11-01T08:22:02.851Z","updatedUtc":"2021-11-01T08:54:25.769Z"}
```

The Swagger it is using is still the same link as before.

**Comment by ffMathy** [comment] 2021-11-01 09:05
The line at which this happens on is:

`Error in function deserializeResponseBody in ./node_modules/@azure/core-client/dist-esm/src/deserializationPolicy.js:101`

**Comment by ffMathy** [comment] 2021-11-09 07:47
@sarangan12 can you reopen this? :pray:

**Comment by sarangan12** [comment] 2022-02-10 19:45
@ffMathy 

Can you please confirm if you still facing this issue?

**Comment by sarangan12** [comment] 2022-02-11 07:47
I am going with the assumption that you are not facing the issue anymore :-) . So, I am closing the issue. Let me know if the issue still exist.

**Closed by sarangan12** 2022-02-11 07:47 UTC
Labels: bug, question, customer-reported, v6, needs-team-attention

**Comment by slavivanov** [comment] 2023-02-17 13:13
- Encounter issue
- Google it
- First result is a github issue
- Issue is closed
- It was closed without resolution
- Cry

**Comment by slavivanov** [comment] 2023-02-17 13:33
To whoever else finds this: in my case it was caused by AnyOf/OneOf which is not supported in autorest at the time.

**Comment by rockstarr-programmerr** [comment] 2023-02-22 08:57
Thanks @slavivanov , it was exactly my problem as well
