### ISSUE TITLE
estree/index has no exported member named ChainExpression

### ISSUE THREAD

**Issue by ffMathy** [Azure/autorest.typescript#1230] opened 2021-10-29 08:59 UTC
When trying to build my package, I get the following error:

```
> tsc && rollup -c 2>&1 && npm run minify && mkdirp ./review && npm run extract-api

../../../node_modules/@types/eslint/index.d.ts:451:42 - error TS2724: '"/workspaces/sponsorkit.io/src/frontend/src/generated/openapi/node_modules/@types/estree/index"' has no exported member named 'ChainExpression'. Did you mean 'ThisExpression'?

451         ChainExpression?: ((node: ESTree.ChainExpression & NodeParentExtension) => void) | undefined;
                                             ~~~~~~~~~~~~~~~

../../../node_modules/@types/eslint/index.d.ts:474:43 - error TS2694: Namespace '"/workspaces/sponsorkit.io/src/frontend/src/generated/openapi/node_modules/@types/estree/index"' has no exported member 'ImportExpression'.

474         ImportExpression?: ((node: ESTree.ImportExpression & NodeParentExtension) => void) | undefined;
                                              ~~~~~~~~~~~~~~~~


Found 2 errors.
```

**Comment by sarangan12** [comment] 2021-11-09 07:45
@ffMathy,

This looks like an issue that is specific to your package/project. I do not see how this could be related to the generator project.

**Comment by ffMathy** [comment] 2021-11-09 07:46
@sarangan12 upgrading to the latest generator solved the issue :shrug:

**Comment by ffMathy** [comment] 2021-11-17 15:09
@sarangan12 I was wrong - I was doing this for the wrong project. This is still relevant.

It happens even if I go directly into the generated code and run `npm run build`, so it shouldn't have anything to do with my project.

I am running Node `16.13.0` and npm `8.1.0`.

**Comment by ffMathy** [comment] 2021-11-26 09:42
@sarangan12 any news on this? It even happens if I move the generated project out of the main project. In other words, it seems to have nothing to do with my own code.

**Comment by ffMathy** [comment] 2021-11-26 09:49
More info on why it might be happening - I think estree needs to be changed in the project Autorest generates.

https://stackoverflow.com/questions/67806963/types-eslint-error-chainexpression-and-importexpression-members-of-estree-not

**Comment by sarangan12** [comment] 2022-01-04 19:10
@ffMathy I am starting to look into this issue. Will keep you posted

**Comment by noherczeg** [comment] 2022-01-08 01:42
The issue is with `@types/eslint` and `@types/estree` incompatibilities. The issue is even worse once one upgrades both to latest...

**Comment by noherczeg** [comment] 2022-01-08 01:55
Not sure if this is an actual fix, but the error goes away, if you add:

```
export interface ThisExpression extends BaseExpression {
  type: "ThisExpression";
}

export interface ImportExpression extends BaseExpression {
  type: "ImportExpression";
}
```

to `@types/estree/index.d.ts`

Given:
- @types/estree: 0.0.39
- @types/eslint: 8.2.2

Obviously this somehow needs to be released an actual fix version in @types/estree.

**Comment by sarangan12** [comment] 2022-02-10 19:42
@ffMathy

The issue is with the @types/estree and @types/eslint packages. With the geneator projects, we do not have any default dependency on @types/eslint package. We do depend on @types/estree (0.0.39) package through @rollup/plugin-commonjs(21.0.1). 

From the conversation at https://stackoverflow.com/questions/25997519/how-to-view-the-dependency-tree-of-a-given-npm-module, the issue gets fixed with latest version of @types/estree. So, I would recommend opening an issue with the https://github.com/rollup/plugins/tree/master/packages/commonjs/ repository to publish a new package with updated estree dependency so it works with the latest eslint.

**Comment by sarangan12** [comment] 2022-02-15 08:05
Closing this issue as this one does not need any action item now. If the issue is solved in rollup, feel free to reopen the issue. Thanks

**Closed by sarangan12** 2022-02-15 08:05 UTC
Labels: question, customer-reported
