### ISSUE TITLE
track1 code generator is generating weird method name for arm-policyinsights

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#1261] opened 2021-12-10 08:01 UTC
We  are trying to generate the mgmt plane track1 sdk for policyinsights RP. The command we are using is 
`autorest --typescript --typescript-sdks-folder=../azure-sdk-for-js --license-header=MICROSOFT_MIT_NO_VERSION ../azure-rest-api-specs/specification/postgresql/resource-manager/readme.md --use=@microsoft.azure/autorest.typescript@4.7.0`

And we get some weird method names like nextLink1, nextLink2, nextLink3 etc in `sdk/policyinsights/arm-policyinsights/src/operations/policyStates.ts`
![image](https://user-images.githubusercontent.com/55688292/145538028-70a54c97-4a7e-4e36-b893-6c5d210a78bd.png)

we also tried to use @microsoft.azure/autorest.typescript@4.4.4 and @microsoft.azure/autorest.typescript@4.2.2 still not working 

--version:2.0.4417 also doesn't work.

**Comment by sarangan12** [comment] 2021-12-10 18:16
@qiaozha The title and description mentions policyInsights RP. But, the command references the file `../azure-rest-api-specs/specification/postgresql/resource-manager/readme.md` which is related to `postgresql`. Is the command added by mistake?

I am going to try both the SDKs and update this issue.

**Comment by sarangan12** [comment] 2021-12-10 18:25
First, I have tried the postgresql SDK using the following command:

```
autorest --typescript --typescript-sdks-folder=C:\Users\sarajama\Projects\azure-sdk-for-js --license-header=MICROSOFT_MIT_NO_VERSION --use=@microsoft.azure/autorest.typescript@4.7.0 --title=PostgreSQLFlexibleManagementClient C:\Users\sarajama\Projects\azure-rest-api-specs\specification\postgresql\resource-manager\readme.md
SourceMapConsumer.initialize is a no-op when running in node.js
AutoRest code generation utility [cli version: 3.5.1; node: v14.15.4]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
info    | AutoRest core version selected from configuration: ~2.0.4413.
   Loading AutoRest core      'C:\Users\sarajama\.autorest\@microsoft.azureautorest-core@2.0.4421\nodemodules\@microsoft.azure\autorest-core\dist' (2.0.4421)
   Loading AutoRest extension '@microsoft.azure/autorest.typescript' (4.7.0->4.7.0)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.51->2.3.51)
INFORMATION: Getting the package version from the pre-existing package.json file in the output folder.
INFORMATION: Got version "1.0.0" for package "@azure/arm-postgresql-flexible" from existing package.json file.
```

The generation was successful. Build was successful. There is no reference to any names such as `nextLink2`, `nextLink3', etc. So, there is no problem with postgresql. 

I am going to try the policyInsights and update the issue.

**Comment by sarangan12** [comment] 2021-12-10 18:33
Used the following command to generate `policyInsights` RP:

```
autorest --typescript --typescript-sdks-folder=C:\Users\sarajama\Projects\azure-sdk-for-js --license-header=MICROSOFT_MIT_NO_VERSION --use=@microsoft.azure/autorest.typescript@4.7.0  C:\Users\sarajama\Projects\azure-rest-api-specs\specification\policyinsights\resource-manager\readme.md
SourceMapConsumer.initialize is a no-op when running in node.js
AutoRest code generation utility [cli version: 3.5.1; node: v14.15.4]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
info    | AutoRest core version selected from configuration: ~2.0.4413.
   Loading AutoRest core      'C:\Users\sarajama\.autorest\@microsoft.azureautorest-core@2.0.4421\nodemodules\@microsoft.azure\autorest-core\dist' (2.0.4421)
   Loading AutoRest extension '@microsoft.azure/autorest.typescript' (4.7.0->4.7.0)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.51->2.3.51)
INFORMATION: Getting the package version from the pre-existing package.json file in the output folder.
INFORMATION: Got version "4.0.0" for package "@azure/arm-policyinsights" from existing package.json file
```

I was able to generate and build the SDK. But, I see the `nextLink`, `nextLink2`, `nextLink3` in the generated SDK and this has to be fixed. Let me work on it and update this issue.

**Comment by sarangan12** [comment] 2021-12-10 22:19
I have checked the generated SDK and the swagger provided. Here, this issue started happening from commit id: `b189836eb664ef8d660ccf761a4111bee19ad840` which was committed on May 24, 2021 in this PR: https://github.com/Azure/azure-rest-api-specs/pull/14035

Let me give an example. Take a look at this [file](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/policyinsights/resource-manager/Microsoft.PolicyInsights/stable/2019-10-01/policyStates.json#L35). The operation id is `PolicyStates_ListQueryResultsForManagementGroup`. But, with the above mentioned commit id, the following line is added:

```
"x-ms-pageable": {
  "nextLinkName": "@odata.nextLink",
  "operationName": "PolicyStates_NextLink"
}
```

As you can see, the operation name is overridden and set to `NextLink`. This is happening at 9 places in the same file. which resulted in names such as `nextLink`, `nextLink1`, etc.  

So, there is no issue on the generator side. The issue is with the swagger. 

Now, why was this done? I think service team would be the best to answer that question. 

How do we solve this?
I have checked the Java SDK for policyInsights RP. To the best of my understanding, Java SDK does not follow the JS Logic. So, they do not have this problem. So, our generator might have this problem. But, since this is a old version and possibly be out of date in the next few months (@ramya-rao-a Please share your thoughts) I would not go ahead with code fix here. 

Instead, please do a swagger transform that overrides the `operationName` which will solve your problem. 

Please let me know if this solves your problem or if you need any more details. Thanks

**Comment by ramya-rao-a** [comment] 2021-12-11 02:06
If a swagger transform can help here, I would recommend that route given that this issue is for the older generator.

Can we check whether the new generator will have the same problem?

**Comment by sarangan12** [comment] 2021-12-11 02:25
@ramya-rao-a Forgot to mention that. The error does not happen with the latest generator (However this SDK needs leniant model dupliction flag, which is not unrelated)

**Comment by qiaozha** [comment] 2021-12-13 02:44
@sarangan12 Thanks for such detailed investigation here, let me check with service team about this and get back to you. I think we can hold on the fix for it here until we get more information from service team.

**Comment by sarangan12** [comment] 2022-01-06 23:44
@qiaozha is there any update from the service team?

**Comment by sarangan12** [comment] 2022-03-03 07:09
@qiaozha As there are no pending action items, I am closing this task. If you find anything new from the Service Team and would like to update the generator, feel free to reopen this task.

**Closed by sarangan12** 2022-03-03 07:09 UTC
Labels: v4

**Comment by qiaozha** [comment] 2022-03-03 07:30
> @qiaozha As there are no pending action items, I am closing this task. If you find anything new from the Service Team and would like to update the generator, feel free to reopen this task.

Yes, it's okay to close it, We decide to release track2 SDK directly for this RP which works as expected. Thanks
