### ISSUE TITLE
[Typespec] Request body should not be optional

### ISSUE THREAD

**Issue by HarshaNalluru** [Azure/autorest.typescript#2133] opened 2023-11-17 20:29 UTC
Request bodies should not be optional
```ts
export interface AnalyzeDocumentBodyParam {
  /** Analyze request parameters. */
  body?: AnalyzeDocumentRequest;
}
```

Source https://github.com/Azure/azure-rest-api-specs/blob/eaf8b6f8e3ae429c8100471a9772a4bee9a5e472/specification/ai/DocumentIntelligence/routes.tsp#L161-L174

**Comment by MaryGao** [comment] 2023-11-20 02:28
@HarshaNalluru Just curious why the body should not be optional, I notice the typespec def is optional

```
analyzeDocument is DocumentIntelligenceLongRunningOperation<
    {
      ...DocumentModelAnalyzeRequestParams;

      @doc("Input content type")
      @header
      contentType: "application/json";

      @doc("Analyze request parameters.")
      @body
      analyzeRequest?: AnalyzeDocumentRequest; // <========== Here is optional body
    },
    AnalyzeResultOperation
  >;
```

**Comment by MaryGao** [comment] 2024-07-25 13:43
@HarshaNalluru close this because this is by design and let me know if any concern.

**Closed by MaryGao** 2024-07-25 13:43 UTC
Labels: P1, RLC
