### ISSUE TITLE
[Modular] Implement Pagination

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#1856] opened 2023-05-18 01:35 UTC
Say we have below tsp definition
```
  @doc("List Widget resources")
  listWidgets is Operations.ResourceList<
    Widget,
    ListQueryParametersTrait<StandardListQueryParameters & SelectQueryParameter>
  >;
```

We would expect to generate modular operation

```typescript
  public listWidgets(
    options?: ListWidgetsOptionalParams
  ): PagedAsyncIterableIterator<Widget> 
```

### Option 1: One paging helper per operation

```typescript
public listWidgets(
    options?: ListWidgetsOptionalParams
  ): PagedAsyncIterableIterator<Widget> {
    const iter = this.__listWidgetsPagingAll(options);
    return {
      next() {
        return iter.next();
      },
      [Symbol.asyncIterator]() {
        return this;
      },
      byPage: (settings?: PageSettings) => {
        if (settings?.maxPageSize) {
          throw new Error("maxPageSize is not supported by this operation.");
        }
        return this.getEmptyNextLinkNamePagesPagingPage(options, settings);
      }
    };
  }


private async __listWidgetsPagingAll(
    options?: ListWidgetsOptionalParams
  ): AsyncIterableIterator<Widget> {
    ....
  }
```

### Option 2: Leverage pagination helper in RLC
```typescript
  public listWidgets(
    options?: ListWidgetsOptionalParams
  ): PagedAsyncIterableIterator<Widget> {
    const initialResponse = await _listWidgetsSend(
        context,
        options
      );
    return paginate(client, initialResponse, {
         customGetPage: () => { ... // deserilized logic}
   });
}
```

### Option 3: A modular generator
See details as below.

**Comment by joheredi** [comment] 2023-05-26 21:14
I think option 2 makes sense to start with. Assuming we can enhance it to support all paging scenarios. We can work afterwards to see if we want to optimize further by moving to option#3 but that would depend on bundle size analysis to decide if the gains are worth the effort.

**Comment by MaryGao** [comment] 2023-08-18 06:53
Take this as high priority considering the content safety would have paging operations. Previously we proposed two options and I have some concerns and I think we could have third one.

**Option 1: Similar to HLC's implementations**

This way we have to build everything by ourselves and I don't think that is necessary because we have [the getPagedAsyncIterator util](https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/core/core-paging/src/getPagedAsyncIterator.ts#L14) in core-paging.

**Option 2: Leverage RLC's paginate helper**

The only concern for me to leverage [the RLC helper](https://github.com/Azure/autorest.typescript/blob/a25c888a1d0deca8ff657267bde5b5ac9a9e78b9/packages/typespec-ts/test/modularIntegration/generated/azure/core/src/rest/paginateHelper.ts#L65) is that it would trigger the initial request when customers get the async iterator not when they begin to iterate the values by `.next()`. I notice that [the asynchronous Iterators proposal](https://github.com/tc39/proposal-async-iteration#asynchronous-iterators-for-javascript) didn't mention this is expected or not, but it somehow goes against my intuition because a [general generotor function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator) would be called only when we call .next.

```typescript
const iter = client.listWidgets();  // >>>>>>>>>>>>>>>> the inital request would be triggered here
const resArray = new Array();
for await (let item of iter) {
  resArray.push(item);
}
```

**Option 3: Build an modular paging generator**

So I prefer we could have an independent and internal paging generator for each operation by leverage the `getPagedAsyncIterator` in core-paging. In that generator we could call relevant serialization and deserialization functions to build the results.

```typescript
export function listWithPage(
  context: Client,
  options: ListWithPageOptions = { requestOptions: {} }
): PagedAsyncIterableIterator<Page> {
  return listWithPageGenerator(context, options);
}

function listWithPageGenerator(
  context: Client,
  options: ListWithPageOptions
): PagedAsyncIterableIterator<Page> {
  const pagedResult: PagedResult<Page[]> = {...}；
  return getPagedAsyncIterator(pagedResult);
}
```

**Comment by qiaozha** [comment] 2023-08-18 08:50
no objections from me for Option 3, just feel the top level [pageHelper.ts](https://github.com/Azure/autorest.typescript/pull/1978/commits/a25c888a1d0deca8ff657267bde5b5ac9a9e78b9#diff-2fd514b1f6e14dbd990f86f9ddb5f6e1e0d170bdafafd077222a6a29973d7b33) is not necessary  we can either export those functions from RLC paginateHelper or put them into core-paging.

**Comment by deyaaeldeen** [comment] 2023-08-18 18:19
I would go with re-using the RLC helper. Notice that you can customize it using this option: https://github.com/Azure/autorest.typescript/blob/b38e9e21f57d31876194a40a688ccae6e2438b53/packages/typespec-test/test/confidentialLedger/generated/typespec-ts/src/paginateHelper.ts#L38

**Comment by xirzec** [comment] 2023-08-18 19:00
First, to check my understanding of the situation: the RLC pagination helper is called by the consumer on the result of an operation, so we have an initial response. Directly re-using this function would cause us to need to call the list operation once before we get back the iterator shape, which Mary points out may not be desired/expected.

To work around this, we are building it slightly differently such that `getPagedAsyncIterator` is able to return the iterator contract prior to the first page being fetched.

Since both approaches (the paginate helper and this new variant) seem to overlap greatly in what they support, perhaps we could tweak the code in the RLC helper slightly such that we can have support for either pattern or at least build `paginate` on top of some common method we can use for this "query on next()" scenario.

Does that seem reasonable?

**Comment by qiaozha** [comment] 2023-08-19 01:47
Maybe we can consider pass the _Send function and _Deserialize function as parameters to the paginateHelper.  Similar like Option3 but move those logic into paginate function in a more generic way.

```typescript 
export function paginate<TResponse extends PathUncheckedResponse>(
  client: Client,
  sendInitialRequest: () => Promise<TResponse>,
  deserialize: (response: TResponse) => Promise<TResponse>,
  options: PagingOptions<TResponse> = {}
): PagedAsyncIterableIterator<PaginateReturn<TResponse>> {
  // Extract element type from initial response
  type TElement = PaginateReturn<TResponse>;
  let firstRun = true;
  // We need to check the response for success before trying to inspect it looking for
  // the properties to use for nextLink and itemName
  const { customGetPage } = options;
  const pagedResult: PagedResult<TElement[]> = {
    firstPageLink: "",
    getPage:
      typeof customGetPage === "function"
        ? customGetPage
        : async (pageLink: string) => {
            const result = firstRun
              ? await sendInitialRequest()
              : ((await client.pathUnchecked(pageLink).get()) as TResponse);
            firstRun = false;
            const { itemName, nextLinkName } = getPaginationProperties(result);
            const nextLink = getNextLink(result.body, nextLinkName);
            const values = getElements<TElement>(
              await deserialize(result),
              itemName
            );
            return {
              page: values,
              nextPageLink: nextLink
            };
          }
  };

  return getPagedAsyncIterator(pagedResult);
}
```

One concern is the deserialize function should take RLC response type and returns Modular response type , not sure if define it as  `deserialize: (response: TResponse) => Promise<TResponse>` works or not.  Maybe `deserialize: (response: TResponse) => Promise<unknown> ` as in TResponse the body is unknown type.

Also, we need to consider the backward compatible for the current paginateHelper in RLC.

**Comment by MaryGao** [comment] 2023-08-21 13:12
Agreed that we could improve the RLC paginate, similar to Qiaoqiao's proposal I would like to adjust a little bit to make it more generic for RLC.

**RLC paginate**
Add an overload to accept the `initialCall` as parameter and also add the `deserializeCallback` and `initialCallArgs` into optional bags as it is not required in all cases.

- An overload to paginate function
https://github.com/Azure/autorest.typescript/blob/3bf6da386dd6cdc22206a2a3202991739bd5ef84/packages/typespec-ts/test/modularIntegration/generated/azure/core/src/rest/paginateHelper.ts#L81-L86

- Optional params
https://github.com/Azure/autorest.typescript/blob/3bf6da386dd6cdc22206a2a3202991739bd5ef84/packages/typespec-ts/test/modularIntegration/generated/azure/core/src/rest/paginateHelper.ts#L39-L42

**Modular operation**

Directly call RLC paginate to prepare the iterator.

- operations.ts
https://github.com/Azure/autorest.typescript/blob/3bf6da386dd6cdc22206a2a3202991739bd5ef84/packages/typespec-ts/test/modularIntegration/generated/azure/core/src/api/operations.ts#L269-L272

Feel free to comment if more suggestions, if no I will take this as finalized design!

**Comment by deyaaeldeen** [comment] 2023-08-21 16:48
I wanted to bring up my proposal above again before diving into a more complicated solution. Could we modify `paginate` such that the initial response is optional. Then we can simply use `customGetPage` to send the initial request too? I think this succinctly captures what Jeff was suggesting in his comment.

**Comment by MaryGao** [comment] 2023-08-22 02:43
I prefer to have the overload to start with and here are my reasons:
- there will be a lot overlapping in `customGetPage` and these duplications could be avoided with slightly improving RLC paginate
- pure RLC customers could also pass their inital call no need to `await` initial response
- modular code would be simple enough to satisfy current cases

And assume we would implement all paging cases which may not handle them well we could go to `customGetPage` for complicated customizations. Does it make sense to you?

**Comment by MaryGao** [comment] 2023-08-23 00:19
Summerize our proposals:
**Option 1: Add an overload in RLC**
Pro
- Minimal duplications
- Reuse well in modular

Cons
- New API is added which may complicate customers and make it hard to maneuver around it in the future when new requirements arises

**Option 2: Make the initial reponse optional and use `customGetPage`**
Pro
- minimal change in RLC to accept modular case

Cons
- duplications - most of logic are in customGetPage so we can't reuse them well
- making the initialResponse optional could confuse customers because there is only one required param `client`
```
export function paginate<TResponse extends PathUncheckedResponse>(
  client: Client,
  initialResponse?: TResponse,
  options?: PagingOptions<TResponse>
)
```

**Option 3: Generate the overload helper in Modular**
This way modular will not use the RLC help and we could generate its own helper that is the overload one in modular.

Pro
- no new api will be impacted in RLC

Con
- duplications in between

**Comment by bterlson** [comment] 2023-08-23 18:21
I don't think we should be adding or changing public APIs without a strong customer focused justification. While it's nice to be able to share more code, I don't think this is sufficient justification to add additional complexity to user-facing APIs.

**Comment by MaryGao** [comment] 2023-08-23 23:31
Thanks Brian's suggestion! Currently we didn't find a perferct way to leverage RLC paginate without changing public API so I'd like to start with Option 3 to build an internal helper in modular.

**Comment by MaryGao** [comment] 2023-09-08 09:42
**Background**

For list operations result sets may be massive so customers may retrieve them page by page according to continuation token. Currently our `byPage` interface only offers the page data without any continuation token info and we provide the helper `getContinuationToken` to cache these details. In modular we could adjust the interface to better facilitate this feature and this could cause breaking changes.

**`byPage` interface change**

- **Current interface in HLC**

operations.ts
```typescript
import { PagedAsyncIterableIterator } from "@azure/core-paging";
list(
  options?: ListOptionalParams
): PagedAsyncIterableIterator<Product>;
```

models.ts in core-paging [code](https://github.com/Azure/azure-sdk-for-js/blob/b8fa565e3744eb00503c58bc46562aa88b7fe9e5/sdk/core/core-paging/src/models.ts#L36)

```typescript
export interface PagedAsyncIterableIterator
 //...
 byPage: (settings?: TPageSettings) => AsyncIterableIterator<TPage>; 
}

export interface PageSettings {
  continuationToken?: string;
  maxPageSize?: number;
}
```

- **New interface in modular**

operations.ts
```typescript
// 1. Name is the same as core-paging but it is defined in SDK side
import { PagedAsyncIterableIterator } from "../models/index.js";
list(
  options?: ListOptionalParams
): PagedAsyncIterableIterator<Product>;
```

models.ts in SDK
```typescript
// 2. A new model used as the return type of byPage
export interface ContinuablePage<TPage, TLink = string> {
  /**
   * Gets a list of elements in the page.
   */
  page: TPage;
  /**
   * The token that keeps track of where to continue the iterator
   */
  continuationToken?: TLink;
}

export interface PagedAsyncIterableIterator
 //...
 byPage: (
    settings?: TPageSettings
 // 3. Return type is changed from TPage to ContinuablePage
  ) => AsyncIterableIterator<ContinuablePage<TPage>>;
}

// 4. maxPageSize is removed directly
export interface PageSettings {
  continuationToken?: string;
}
```
**Other Considerations**

**Comment by xirzec** [comment] 2023-09-08 15:16
I like removing `maxPageSize` since any such parameter can still be part of the original list call if the service supports it without needing to be included in a call to `byPage`.

I also like `ContinuablePage` as it makes the `continuationToken` much more discoverable. Can we remove the `TLink` parameter and enforce that `continuationToken` is simply an optional `string` instead? Otherwise, the consumer would have to somehow turn it into a string in order to pass it into `PageSettings`.

One thing I'm curious about is point 3 in your example, changing from `AsyncIterableIterator` to `AsyncIterator`. The main difference between these types being that the `AsyncIterableIterator` is compatible with anything that expects an interable rather than an iterator, that is to say, I'm not sure if `for/of` will work correctly if you pass it an iterator directly. The main advantage of iterable iterators is that they're useful by constructors like `for/of` as well as directly consumable by a developer who wishes to call `next()` manually.

I have also been thinking about the compatibility problem with previously shipped clients. I wonder if we could include some way to opt into a `ContinuablePage` result, perhaps through another page setting, though I think writing the TypeScript for this is difficult. Failing that, we could imagine a companion function to `byPage` like `byContinuablePage` or some such.

**Comment by MaryGao** [comment] 2023-09-11 16:07
Thanks Jeff's suggestion!
> Can we remove the TLink parameter and enforce that continuationToken is simply an optional string instead?

Sure let's keep it simple with string.

> Changing from AsyncIterableIterator to AsyncIterator

Yeah, I think we should keep `AsyncIterableIterator` and I may mis-understand this part previously.

> I wonder if we could include some way to opt into a ContinuablePage result.

I am also thinking about this and I think adding a companion function would work for me. Another immature idea is that `ContinuablePage` could extend `TPage` so that we could keep the backward compatible.

**Comment by MaryGao** [comment] 2023-09-12 01:13
Offline confirmed we could look at having it extend the page type so someone returning Array<Model> could return Array<Model> & { continuationToken: string } but should be careful for the performance impact.

**Closed** 2023-11-28 02:16 UTC
Labels: priority-0, Mgmt, HRLC, DPG/RLC v2.1
