### ISSUE TITLE
Response missed in Track2 SDK

### ISSUE THREAD

**Issue by dw511214992** [Azure/autorest.typescript#1037] opened 2021-06-15 09:20 UTC
Swagger: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/Microsoft.Resources/stable/2020-10-01/resources.json#L2430-L2468

Track1:

Method:
```
checkExistence(resourceGroupName: string, options?: ResourceGroupsCheckExistenceOptionalParams):Promise<Models.ResourceGroupsCheckExistenceResponse>;
```
Response Model:
```
export type ResourceGroupsCheckExistenceResponse = {
    /**
     * The parsed response body.
     */
    body: boolean;
    /**
     * The underlying HTTP response.
     */
    _response: msRest.HttpResponse & {
        /**
         * The response body as text (string format)
         */
        bodyAsText: string;
        /**
         * The response body as parsed JSON or XML
         */
        parsedBody: boolean;
    };
};
```
Track2:
```
checkExistence(resourceGroupName: string, options?: ResourceGroupsCheckExistenceOptionalParams):Promise<void>;
```
Comparing the responses of methods in Track1 and Track2, we can find there is no response in Track2 and we cannot get any information from the rest api.

**Comment by deyaaeldeen** [comment] 2021-06-15 18:42
I am looking at the swagger here: https://github.com/Azure/azure-rest-api-specs/blob/61e7148e9592c5efc95e5c16a5bb4f2dc26d6de0/specification/resources/resource-manager/Microsoft.Resources/stable/2020-10-01/resources.json#L2454. Why the responses section does not have an entry for 200?

**Comment by sarangan12** [comment] 2021-06-17 08:23
@dw511214992 I have looked into this issue and the swagger. I agree that the V4 version of the SDK is producing a body of type boolean. But, per swagger there is no body defined. So, I will consider the V4 version only as a bug. The V6 version is working correctly per the swagger. 

Also, I have checked the operation spec in the v4 generator. So, even though the response has a body I do not see it getting deserialized and used. So, if this is a bug that should be fixed, then it should be fixed in V4. Not V6.

Could you please explain, if there is a problem if body-boolean is removed in v6?

**Comment by dw511214992** [comment] 2021-06-18 01:54
hi @sarangan12 If the method returns `Promise<void>`, I cannot get the result of the rest api call. So how can I check wether the service existis or not in `checkExistence(resourceGroupName: string, options?: ResourceGroupsCheckExistenceOptionalParams):Promise<void>;`?

**Comment by sarangan12** [comment] 2021-06-21 03:17
@dw511214992 Agreed. Even in v4, the operationSpec does not have anything related. So, the `body` will not be deserialized at all.

I agree that there has to be a body. My point is that such a thing must be mentioned in the swagger. In this case, it is not mentioned at all.

**Comment by dw511214992** [comment] 2021-06-21 03:35
@sarangan12 I think the swagger definition is correct. User can check wether the resource exists by the response code: `200` represents `Found` and `404` represents `Not Found`. So I think Codegen should handle this as a special case. How do you think? thanks

**Comment by sarangan12** [comment] 2021-06-21 08:38
The response code `204` and `404` themselves do not represent anything by themselves. They need a body defined to make that happen. 

I will try hunting down the logic in v4 if any such thing is happening. To the best of my knowledge, nothing like that happens which makes me suspect that something might be happening in autorest core. I will discuss with autorest crew and get back to you.

**Comment by dw511214992** [comment] 2021-06-21 08:57
thanks @sarangan12

**Comment by sarangan12** [comment] 2021-07-02 06:50
@dw511214992 I have confirmed with autorest crew that this logic has been removed V3 version of autorest. Now, the only way to do this is on the generator side. I have analyzed the required code changes to do this. It would create complexity in the code. On the other hand, the same result could be easily achieved by the swagger transform as:

```yaml
directive:
  - from: swagger-document
    where: $.paths..head.responses['204']
    transform: >
      $.schema = {};
      $.schema["$ref"] = "#/definitions/ResourceGroupsCheckExistenceResponse";
  - from: swagger-document
    where: $.definitions
    transform: >
      $.ResourceGroupsCheckExistenceResponse = {};
      $.ResourceGroupsCheckExistenceResponse.type = 'object';
      $.ResourceGroupsCheckExistenceResponse.properties = {};
      $.ResourceGroupsCheckExistenceResponse.properties.body = {};
      $.ResourceGroupsCheckExistenceResponse.properties.body.type = 'boolean';
```

Please share your thoughts on using the above swagger transform. Thanks

**Comment by dw511214992** [comment] 2021-07-02 08:49
@sarangan12 Although the change can solve this issue, I have some other concerns about this change:
1. I worry whether the change leads to breaking changes to other sdk.
2. It's reasonable to define response with 204 No Content, which doesn't contain a body.
3. I worry there are many swaggers having this kind of response, and it's not easy to change all the swaggers. If this change leads to breaking change for other sdks, I think it's impossible to change all of them.
What do you think about it? thanks

**Comment by sarangan12** [comment] 2021-07-02 16:37
@dw511214992 
1. It will not lead to any breaking changes to other SDKs. So, that is not a problem. 
2. I agree it is reasonable to define a response with 204 No Content which doesn't contain a body. Our transformations, in general, are not to fix incorrect swaggers. They are to modify certain parts to fit the requirements of SDK. This would be a perfect candidate.
3. This is a valid concern. I think with more number of migrations, it might be an issue. 

So, here is my suggestion. I will work on fixing this issue for August release (July release timeframe is already over). Until then, you need not be blocked by this issue. You could continue migrating resources SDK using the transformations as a stop-gap measure. Does that sound good?

**Comment by dw511214992** [comment] 2021-07-05 02:00
@sarangan12 Yes, sounds good for me. Could you please create a PR for you transformations in swagger repository? I will review it. Thanks

**Comment by dw511214992** [comment] 2021-07-06 09:10
@sarangan12 I have mode the changes in swagger readme.md and generated the package. However, the package doesn't work.
The test code we use is:
```
import * as res from "@azure/arm-resources";
import { DefaultAzureCredential} from "@azure/identity";

var subscriptionId = process.env.subscriptionId;

var credential = new DefaultAzureCredential();

class Test{

    private client = new resources.ResourceManagementClient(credential,subscriptionId);

    public async test(){
        const result = await this.client.resourceGroups.checkExistence("qiaozhatest");
        console.log(result);
    }
}

const t = new Test();

t.test();
```
When we use the track1 package, it works as expect and prints: `{body: true}`
When we use the track2 package, it prints `undefined` immediately and then the program is stuck for a while.

So I think the generated codes is incorrect when adding this kind of directive. thanks

**Comment by sarangan12** [comment] 2021-07-15 16:33
Summary:

This issue is the result of 2 items:

1. In the v4x generator, the Autorest Modelerfour handled the required transformations and `body:boolean;` was readily available for the generators. But, in the v6x generator, the Modelerfour stopped this transformation. Alternatively, a new flag called `head-as-boolean` is introduced. The inidividual generators should handle the required code change. (These changes are completed as part of the PR: https://github.com/Azure/autorest.typescript/pull/1101. 
2. Even with the above code change, the `HEAD` HttpRequest will not be handled correctly. **Why?** Because, in the v4x generator, the ms-rest-js handles the `HEAD` request case [here](https://github.com/Azure/ms-rest-js/blob/master/lib/serviceClient.ts#L813). Such a change is missing in the `core-client` & `core-rest-pipeline` packages. (The changes are already available in `core-http` package). (These changes are completed as part of the PR:https://github.com/Azure/azure-sdk-for-js/pull/16363. 

With the above PRs merged, a new version of `@autorest/typescript` package has been released. With the new version, the code is working fine. No more action items pending on this issue.

**Closed by sarangan12** 2021-07-15 16:33 UTC
