### ISSUE TITLE
Fail to generate ApiCenter.Management code

### ISSUE THREAD

**Issue by v-jiaodi** [Azure/autorest.typescript#2390] opened 2024-03-27 08:25 UTC
Generation error:
![image](https://github.com/Azure/autorest.typescript/assets/80496810/24749cc5-0811-4c7e-8a22-ea3afd861828)

**Comment by MaryGao** [comment] 2024-05-13 02:10
The root cause is tracked by the issue https://github.com/Azure/autorest.typescript/issues/2492, close this as suplicated.

**Closed by MaryGao** 2024-05-13 02:10 UTC
Labels: HRLC, p0
